# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "ADDRESS" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,"PERSON_ID" INTEGER NOT NULL,"address1" VARCHAR NOT NULL,"state" VARCHAR NOT NULL);
create table "PERSON" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,"name" VARCHAR NOT NULL,"age" INTEGER NOT NULL);
alter table "ADDRESS" add constraint "PERSON_FK" foreign key("PERSON_ID") references "PERSON"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "ADDRESS" drop constraint "PERSON_FK";
drop table "ADDRESS";
drop table "PERSON";

